// SPDX-License-Identifier: MIT OR APACHE2
#pragma once

#define N(x) (x)

#define Vector_GET1(vec, index) ((vec).index)
#define Vector_GET2(vec, index) ((vec).index)
#define Vector_GET4(vec, index) ((vec).index)
#define Vector_GET8(vec, index) ((vec).index)

#define Vector_mkchar2x1(a,b) ((char2)(a,b))
#define Vector_mkchar3x1(a,b,c) ((char3)(a,b,c))
#define Vector_mkchar4x1(a,b,c,d) ((char4)(a,b,c,d))
#define Vector_mkchar4x2(a,b) ((char4)(a,b))
#define Vector_mkchar8x1(a,b,c,d,e,f,g,h) ((char8)(a,b,c,d,e,f,g,h))
#define Vector_mkchar8x2(a,b,c,d) ((char8)(a,b,c,d))
#define Vector_mkchar8x4(a,b) ((char8)(a,b))
#define Vector_mkchar16x1(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p) ((char16)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p))
#define Vector_mkchar16x2(a,b,c,d,e,f,g,h) ((char16)(a,b,c,d,e,f,g,h))
#define Vector_mkchar16x4(a,b,c,d) ((char16)(a,b,c,d))
#define Vector_mkchar16x8(a,b) ((char16)(a,b))

#define Vector_mkuchar2x1(a,b) ((uchar2)(a,b))
#define Vector_mkuchar3x1(a,b,c) ((uchar3)(a,b,c))
#define Vector_mkuchar4x1(a,b,c,d) ((uchar4)(a,b,c,d))
#define Vector_mkuchar4x2(a,b) ((uchar4)(a,b))
#define Vector_mkuchar8x1(a,b,c,d,e,f,g,h) ((uchar8)(a,b,c,d,e,f,g,h))
#define Vector_mkuchar8x2(a,b,c,d) ((uchar8)(a,b,c,d))
#define Vector_mkuchar8x4(a,b) ((uchar8)(a,b))
#define Vector_mkuchar16x1(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p) ((uchar16)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p))
#define Vector_mkuchar16x2(a,b,c,d,e,f,g,h) ((uchar16)(a,b,c,d,e,f,g,h))
#define Vector_mkuchar16x4(a,b,c,d) ((uchar16)(a,b,c,d))
#define Vector_mkuchar16x8(a,b) ((uchar16)(a,b))

#define Vector_mkshort2x1(a,b) ((short2)(a,b))
#define Vector_mkshort3x1(a,b,c) ((short3)(a,b,c))
#define Vector_mkshort4x1(a,b,c,d) ((short4)(a,b,c,d))
#define Vector_mkshort4x2(a,b) ((short4)(a,b))
#define Vector_mkshort8x1(a,b,c,d,e,f,g,h) ((short8)(a,b,c,d,e,f,g,h))
#define Vector_mkshort8x2(a,b,c,d) ((short8)(a,b,c,d))
#define Vector_mkshort8x4(a,b) ((short8)(a,b))
#define Vector_mkshort16x1(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p) ((short16)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p))
#define Vector_mkshort16x2(a,b,c,d,e,f,g,h) ((short16)(a,b,c,d,e,f,g,h))
#define Vector_mkshort16x4(a,b,c,d) ((short16)(a,b,c,d))
#define Vector_mkshort16x8(a,b) ((short16)(a,b))

#define Vector_mkushort2x1(a,b) ((ushort2)(a,b))
#define Vector_mkushort3x1(a,b,c) ((ushort3)(a,b,c))
#define Vector_mkushort4x1(a,b,c,d) ((ushort4)(a,b,c,d))
#define Vector_mkushort4x2(a,b) ((ushort4)(a,b))
#define Vector_mkushort8x1(a,b,c,d,e,f,g,h) ((ushort8)(a,b,c,d,e,f,g,h))
#define Vector_mkushort8x2(a,b,c,d) ((ushort8)(a,b,c,d))
#define Vector_mkushort8x4(a,b) ((ushort8)(a,b))
#define Vector_mkushort16x1(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p) ((ushort16)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p))
#define Vector_mkushort16x2(a,b,c,d,e,f,g,h) ((ushort16)(a,b,c,d,e,f,g,h))
#define Vector_mkushort16x4(a,b,c,d) ((ushort16)(a,b,c,d))
#define Vector_mkushort16x8(a,b) ((ushort16)(a,b))

#define Vector_mkint2x1(a,b) ((int2)(a,b))
#define Vector_mkint3x1(a,b,c) ((int3)(a,b,c))
#define Vector_mkint4x1(a,b,c,d) ((int4)(a,b,c,d))
#define Vector_mkint4x2(a,b) ((int4)(a,b))
#define Vector_mkint8x1(a,b,c,d,e,f,g,h) ((int8)(a,b,c,d,e,f,g,h))
#define Vector_mkint8x2(a,b,c,d) ((int8)(a,b,c,d))
#define Vector_mkint8x4(a,b) ((int8)(a,b))
#define Vector_mkint16x1(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p) ((int16)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p))
#define Vector_mkint16x2(a,b,c,d,e,f,g,h) ((int16)(a,b,c,d,e,f,g,h))
#define Vector_mkint16x4(a,b,c,d) ((int16)(a,b,c,d))
#define Vector_mkint16x8(a,b) ((int16)(a,b))

#define Vector_mkuint2x1(a,b) ((uint2)(a,b))
#define Vector_mkuint3x1(a,b,c) ((uint3)(a,b,c))
#define Vector_mkuint4x1(a,b,c,d) ((uint4)(a,b,c,d))
#define Vector_mkuint4x2(a,b) ((uint4)(a,b))
#define Vector_mkuint8x1(a,b,c,d,e,f,g,h) ((uint8)(a,b,c,d,e,f,g,h))
#define Vector_mkuint8x2(a,b,c,d) ((uint8)(a,b,c,d))
#define Vector_mkuint8x4(a,b) ((uint8)(a,b))
#define Vector_mkuint16x1(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p) ((uint16)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p))
#define Vector_mkuint16x2(a,b,c,d,e,f,g,h) ((uint16)(a,b,c,d,e,f,g,h))
#define Vector_mkuint16x4(a,b,c,d) ((uint16)(a,b,c,d))
#define Vector_mkuint16x8(a,b) ((uint16)(a,b))

#define Vector_mklong2x1(a,b) ((long2)(a,b))
#define Vector_mklong3x1(a,b,c) ((long3)(a,b,c))
#define Vector_mklong4x1(a,b,c,d) ((long4)(a,b,c,d))
#define Vector_mklong4x2(a,b) ((long4)(a,b))
#define Vector_mklong8x1(a,b,c,d,e,f,g,h) ((long8)(a,b,c,d,e,f,g,h))
#define Vector_mklong8x2(a,b,c,d) ((long8)(a,b,c,d))
#define Vector_mklong8x4(a,b) ((long8)(a,b))
#define Vector_mklong16x1(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p) ((long16)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p))
#define Vector_mklong16x2(a,b,c,d,e,f,g,h) ((long16)(a,b,c,d,e,f,g,h))
#define Vector_mklong16x4(a,b,c,d) ((long16)(a,b,c,d))
#define Vector_mklong16x8(a,b) ((long16)(a,b))

#define Vector_mkulong2x1(a,b) ((ulong2)(a,b))
#define Vector_mkulong3x1(a,b,c) ((ulong3)(a,b,c))
#define Vector_mkulong4x1(a,b,c,d) ((ulong4)(a,b,c,d))
#define Vector_mkulong4x2(a,b) ((ulong4)(a,b))
#define Vector_mkulong8x1(a,b,c,d,e,f,g,h) ((ulong8)(a,b,c,d,e,f,g,h))
#define Vector_mkulong8x2(a,b,c,d) ((ulong8)(a,b,c,d))
#define Vector_mkulong8x4(a,b) ((ulong8)(a,b))
#define Vector_mkulong16x1(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p) ((ulong16)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p))
#define Vector_mkulong16x2(a,b,c,d,e,f,g,h) ((ulong16)(a,b,c,d,e,f,g,h))
#define Vector_mkulong16x4(a,b,c,d) ((ulong16)(a,b,c,d))
#define Vector_mkulong16x8(a,b) ((ulong16)(a,b))

#define Vector_mkfloat2x1(a,b) ((float2)(a,b))
#define Vector_mkfloat3x1(a,b,c) ((float3)(a,b,c))
#define Vector_mkfloat4x1(a,b,c,d) ((float4)(a,b,c,d))
#define Vector_mkfloat4x2(a,b) ((float4)(a,b))
#define Vector_mkfloat8x1(a,b,c,d,e,f,g,h) ((float8)(a,b,c,d,e,f,g,h))
#define Vector_mkfloat8x2(a,b,c,d) ((float8)(a,b,c,d))
#define Vector_mkfloat8x4(a,b) ((float8)(a,b))
#define Vector_mkfloat16x1(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p) ((float16)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p))
#define Vector_mkfloat16x2(a,b,c,d,e,f,g,h) ((float16)(a,b,c,d,e,f,g,h))
#define Vector_mkfloat16x4(a,b,c,d) ((float16)(a,b,c,d))
#define Vector_mkfloat16x8(a,b) ((float16)(a,b))

#define Vector_mkdouble2x1(a,b) ((double2)(a,b))
#define Vector_mkdouble3x1(a,b,c) ((double3)(a,b,c))
#define Vector_mkdouble4x1(a,b,c,d) ((double4)(a,b,c,d))
#define Vector_mkdouble4x2(a,b) ((double4)(a,b))
#define Vector_mkdouble8x1(a,b,c,d,e,f,g,h) ((double8)(a,b,c,d,e,f,g,h))
#define Vector_mkdouble8x2(a,b,c,d) ((double8)(a,b,c,d))
#define Vector_mkdouble8x4(a,b) ((double8)(a,b))
#define Vector_mkdouble16x1(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p) ((double16)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p))
#define Vector_mkdouble16x2(a,b,c,d,e,f,g,h) ((double16)(a,b,c,d,e,f,g,h))
#define Vector_mkdouble16x4(a,b,c,d) ((double16)(a,b,c,d))
#define Vector_mkdouble16x8(a,b) ((double16)(a,b))